name: Postpone Hibernation on Section.io

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  
jobs:
  postpone-hibernation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Section.io Repository
        uses: actions/checkout@v2
        with:
          repository: section-io/section.io
          branch: main

      - name: Install Required Dependencies
        run: |
          npm install node-fetch

      - name: Postpone Hibernation
        env:
          SECTION_IO_TOKEN: ${{ secrets.SECTION_IO_TOKEN }}
        run: |
          node -e "require('child_process').execSync('curl -X POST \
            https://api.section.io/v2/projects/${{ github.event.repository.name }}/actions/hibernation/postpone \
            -H 'Authorization: Bearer $SECTION_IO_TOKEN' \
            -H 'Content-Type: application/json' \
            -d '{\"duration\": 86400}'')"

      - name: Support Manual Start
        env:
          SECTION_IO_TOKEN: ${{ secrets.SECTION_IO_TOKEN }}
        run: |
          node -e "require('child_process').execSync('curl -X POST \
            https://api.section.io/v2/projects/${{ github.event.repository.name }}/actions/hibernation/start \
            -H 'Authorization: Bearer $SECTION_IO_TOKEN' \
            -H 'Content-Type: application/json' \
            -d '{}')"
