name: Postpone Hibernation

on:
  push:
    branches:
      - main
  workflow_dispatch: # 手动触发

jobs:
  postpone-activity:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Postpone Hibernation
      run: |
        import requests
        from datetime import datetime, timedelta

        now = datetime.utcnow()
        tomorrow = now + timedelta(days=1)

        url = "https://api.section.io/v1/sites/43009/hibernation/postpone"

        data = {
            "until_date": tomorrow.strftime('%Y-%m-%d')
        }

        headers = {
            "Authorization": "Bearer 56d115bc-7e7b-41dc-a72e-7fb77d5dd834:159ea93f-8d9d-459f-bee4-03dec7ddda75"
        }

        response = requests.post(url, headers=headers, json=data)

        if response.status_code == 200:
            print("Hibernation postponed successfully")
        else:
            print("Failed to postpone hibernation")

