on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  postpone-hibernation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip
          pip3 install requests

      - name: Get section.io API token
        run: |
          echo $SECTION_IO_API_KEY > sectionio_api_token.txt

      - name: Postpone hibernation
        run: |
          python3 postpone_hibernation.py sectionio_api_token.txt

      - name: Log result
        run: |
          echo "Postpone hibernation succeeded"
