name: Postpone Hibernation

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0时执行
  workflow_dispatch:  # 手动启动

jobs:
  postpone:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute postpone hibernation operation
      run: |
        ENDPOINT="https://1833107456.kube.api.section.io"
        API_KEY="${{ secrets.SECTION_IO_API_KEY }}"
        
        curl -X POST "$ENDPOINT" \
             -H "Authorization: Bearer $API_KEY" \
             -H "Content-Type: application/json" \
             -d '{"action": "postponeHibernation"}'
