name: 自动续期 section.io 项目
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:    

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 获取 section.io 项目信息
        id: get-info
        run: |
          echo "::set-output name=project_id::$(curl -s -X GET https://api.section.io/v2/projects | jq -r '.[] | select(.name == env.PROJECT_NAME) | .id')"
          echo "::set-output name=project_token::$(curl -s -X GET https://api.section.io/v2/projects | jq -r '.[] | select(.name == env.PROJECT_TOKEN) | .token')"
      - name: 续期项目
        uses: sectionio/actions/renew@v1
        with:
          project_id: ${{ steps.get-info.outputs.project_id }}
          project_token: ${{ steps.get-info.outputs.project_token }}
